<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '公司简介';
$typeArr[3] = '企业文化';
$typeArr[4] = '发展历程';
$typeArr[5] = '新闻资讯';
$typeArr[6] = '公司新闻';
$typeArr[7] = '行业新闻';
$typeArr[8] = '产品中心';
$typeArr[9] = '肉禽水产';
$typeArr[10] = '蔬菜水果';
$typeArr[11] = '厨房调料';
$typeArr[12] = '粮油干货';
$typeArr[13] = '营养知识';
$typeArr[14] = '健康饮食';
$typeArr[15] = '营养课程';
$typeArr[16] = '烹饪技巧';
$typeArr[17] = '在线留言';
$typeArr[18] = '联系我们';
$typeArr[19] = '联系方式';
$typeArr[20] = '基地展示';
$typeArr[21] = '幻灯片';
?>