<div class='cubeLink cubeLink5 ' id='cubeNavigation313_cubeLink5' linkid='5' ><a class='cubeLink_a ' href='list.php?tid=[field:id/]'  target='_self' id='cubeLink_a5_cubeNav313' >
                  <div class='cubeLink_bg'></div>
                  <div class='cubeLink_curtain'></div>
                  <div class='cubeLink_ico icon-cube'></div>
                  <div class='cubeLink_text g_link'>
                    <div class='cubeLink_text_p '>[field:typename/]
                      <p class='cubeLink_subText_p'>OL SERVICE</p>
                    </div>
                  </div>
                  </a></div>