<div id='newsLine665' topClassName='top2' topSwitch='off' newsId='665' newsName='[field:title/] ' class='newsLine line icon-gline  wWLine  topFlagLine firstClass wholeLine' >
                  <div id='lineBody665' class='lineBody lineBodyTable'>
                    <div class='wholeLineTFTableCell'>
                      <div class=' g_topFlag g_topFlag1' ></div>
                    </div>
                    <div class='linkTableCell'>
                      <div class='linkTable'><a hidefocus='true' href='view.php?aid=[field:id/]' target=_self >[field:title/] </a></div>
                    </div>
                  </div>
                </div>
                <div class='g_separator separatorLine'></div>