<div id='newsLine669' topClassName='top1' topSwitch='on' newsId='669' newsName='[field:title/]' class='newsLine line icon-gline  wWLineOne  firstClass' > <a class='lineBodyLink' hidefocus='true' href='view.php?aid=[field:id/]' target='_self' style='width:auto;'>
                  <div id='lineBody669' class='lineBody lineBodyPic'>
                    <div class='fontTableCell'>
                      <div class='fontHiddenTable'>
                        <div class='twoLineHidden'>[field:title/]</div>
                      </div>
                    </div>
                    <div class='picTableCell' style='width:50px; height:50px'>
                      <div id='newsImg669' class='newsLeftImg' style='background:url([field:picname/]) no-repeat 0 0; background-size:cover;background-position:center; width:50px; height:50px'> </div>
                    </div>
                  </div>
                  </a> </div>
                <div class='g_separator separatorLine'></div>