<div class='cubeLink cubeLink1 ' id='cubeNavigation313_cubeLink1' linkid='1' ><a class='cubeLink_a ' href='list.php?tid=[field:id/]' style='cursor:default;'  id='cubeLink_a1_cubeNav313' >
                  <div class='cubeLink_bg'></div>
                  <div class='cubeLink_curtain'></div>
                  <div class='cubeLink_ico icon-cube'></div>
                  <div class='cubeLink_text g_link'>
                    <div class='cubeLink_text_p '>[field:typename/]
                      <p class='cubeLink_subText_p'>ABOUT US</p>
                    </div>
                  </div>
                  </a></div>