<?php
$z[0]=Array("global","",499,525);
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",572,594);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",996,1018);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",1347,1368);
$z[3][4]['name']="cfg_sj";
$z[4]=Array("type"," <a id='numberHref_4' href='list.php?tid=[field:id/]'>\r\n        <div class='icon iconClass_4 faisco-icons-message1'></div>\r\n        <div id='describeName_4' class='describe'>在线留言</div>\r\n        </a> ",1667,1909);
$z[4][4]['typeid']="30";

?>