<?php
$z[0]=Array("global","",80,101);
$z[0][4]['name']="cfg_dh";
$z[1]=Array("global","",114,140);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",322,341);
$z[2][4]['name']="cfg_";
$z[3]=Array("global","",414,435);
$z[3][4]['name']="cfg_sj";
$z[4]=Array("type","<li class=\"contact\" onClick=\"location.href='list.php?tid=[field:id/]'\"><span>联系方式</span></li>",470,606);
$z[4][4]['typeid']="18";

?>