<?php
$z[0]=Array("global","",250,271);
$z[0][4]['name']="cfg_dz";
$z[1]=Array("global","",401,422);
$z[1][4]['name']="cfg_dh";
$z[2]=Array("global","",544,571);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("channel","<a href=\"[field:typeurl/]\">[field:typename/]</a> | ",791,891);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[4]=Array("global","",936,962);
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",1019,1043);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("flink","[field:link /]",1197,1245);
$z[6][4]['row']="24";
$z[7]=Array("global","",1471,1492);
$z[7][4]['name']="cfg_qq";
$z[8]=Array("type","<a href=\"[field:typelink /]\">问题在线留言</a>",1641,1727);
$z[8][4]['typeid']="17";
$z[9]=Array("type","<a href=\"[field:typelink /]\">咨询价格表</a>",1829,1912);
$z[9][4]['typeid']="18";
$z[10]=Array("global","",2175,2196);
$z[10][4]['name']="cfg_dh";

?>