<?php
$z[0]=Array("channel","\r\n        <div 1 id='itemSep_103' class='itemSep'></div>\r\n        <div id='navItem_103' class='navItem navItem_103  icon-navItem'><a href='list.php?tid=[field:id/]' _colid='103' id='navbar_103'><span class='navItemName'>[field:typename/]</span></a></div>\r\n        ",391,905);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[0][4]['currentstyle']="<div id='navItem_103' class='navItem navItem_103 itemSelected icon-navItem'><a href='list.php?tid=~id~' ~rel~><span class='navItemName'>~typename~</span></a> </div>";

?>