<?php
$z[0]=Array("global","",164,185);
$z[0][4]['name']="cfg_dh";
$z[1]=Array("global","",303,329);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",357,383);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","(@me==\"\")? @me=\" class='s_nav'\":@me=\"\";",487,576);
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("channel","\r\n        <li><a href=\"[field:typelink/]\"><span>[field:typename/]</span>[field:typename/]</a></li>\r\n        ",620,873);
$z[4][4]['type']="top";
$z[4][4]['currentstyle']="<li><a href='~typelink~' class='s_nav'><span>~typename~</span>~typename~</a></li>";
$z[4][4]['row']="7";

?>