<?php
$z[0]=Array("type"," <a href=\"[field:typelink /]\">[field:typename /]</a>",357,443);
$z[0][4]['typeid']="1";
$z[1]=Array("type"," <a href=\"[field:typelink /]\" class=\"a0\">[field:typename /]</a>",475,573);
$z[1][4]['typeid']="16";
$z[2]=Array("type"," <a href=\"[field:typelink /]\">[field:typename /]</a>",623,710);
$z[2][4]['typeid']="17";
$z[3]=Array("type"," <a href=\"[field:typelink /]\">[field:typename /]</a>",731,818);
$z[3][4]['typeid']="18";
$z[4]=Array("type"," <a href=\"[field:typelink /]\">[field:typename /]</a>",839,926);
$z[4][4]['typeid']="34";
$z[5]=Array("type"," <a href=\"[field:typelink /]\">[field:typename /]</a>",977,1064);
$z[5][4]['typeid']="31";
$z[6]=Array("type"," <a href=\"[field:typelink /]\" class=\"a0\">[field:typename /]</a>",1096,1194);
$z[6][4]['typeid']="11";
$z[7]=Array("type"," <a href=\"[field:typelink /]\" class=\"a0\">[field:typename /]</a>",1226,1324);
$z[7][4]['typeid']="30";
$z[8]=Array("type"," <a href=\"[field:typelink /]\" class=\"a0\">[field:typename /]</a>",1355,1453);
$z[8][4]['typeid']="19";

?>