<?php
$z[0]=Array("global","",232,258);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",311,341);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",378,405);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",922,958);
$z[3][4]['filename']="nav_m.htm";
$z[4]=Array("type"," <li> <a href=\"list.php?tid=[field:id/]\"> <img src=\"/style/m/images/cp.png\" alt=\"[field:typename /]\">\r\n      <p>[field:typename /]</p>\r\n      </a> </li>",2623,2809);
$z[4][4]['typeid']="1";
$z[5]=Array("type","<li> <a href=\"list.php?tid=[field:id/]\"> <img src=\"/style/m/images/pp.png\" alt=\"[field:typename /]\">\r\n      <p>[field:typename /]</p>\r\n      </a> </li>",2815,3000);
$z[5][4]['typeid']="3";
$z[6]=Array("type","<li> <a href=\"list.php?tid=[field:id/]\"> <img src=\"/style/m/images/server.png\" alt=\"[field:typename /]\">\r\n      <p>[field:typename /]</p>\r\n      </a> </li>",3006,3195);
$z[6][4]['typeid']="4";
$z[7]=Array("type"," <li> <a href=\"list.php?tid=[field:id/]\"> <img src=\"/style/m/images/news.png\" alt=\"[field:typename /]\">\r\n      <p>[field:typename /]</p>\r\n      </a> </li>",3200,3389);
$z[7][4]['typeid']="20";
$z[8]=Array("type","<li class=\"current\"> <a href=\"list.php?tid=[field:id/]\"> <span><img src=\"/style/m/images/rx.png\" alt=\"[field:typename /]\"></span> <b>[field:typename /]</b>\r\n      <p>HOT PEODUCTS</p>\r\n      </a> </li>",3440,3674);
$z[8][4]['typeid']="9";
$z[9]=Array("type","<li> <a href=\"list.php?tid=[field:id/]\"> <span><img src=\"/style/m/images/xp.png\" alt=\"[field:typename /]\"></span> <b>[field:typename /]</b>\r\n      <p>NEWS PEODUCTS</p>\r\n      </a> </li>",3680,3900);
$z[9][4]['typeid']="10";
$z[10]=Array("type","<li> <a href=\"list.php?tid=[field:id/]\"> <span><img src=\"/style/m/images/tj.png\" alt=\"[field:typename /]\"></span> <b>[field:typename /]</b>\r\n      <p>SPECIAL</p>\r\n      </a> </li>",3906,4120);
$z[10][4]['typeid']="11";
$z[11]=Array("type","<li> <a href=\"list.php?tid=[field:id/]\"> <span><img src=\"/style/m/images/cx.png\" alt=\"[field:typename /]\"></span> <b>[field:typename /]</b>\r\n      <p>PROMOTIONAL</p>\r\n      </a> </li>",4126,4344);
$z[11][4]['typeid']="12";
$z[12]=Array("type","\r\n    <h3>[field:typename /]</h3>\r\n    <span class=\"more\"><a href=\"list.php?tid=[field:id/]\">MORE+</a> </span>",4410,4554);
$z[12][4]['typeid']="8";
$z[13]=Array("arclist","\r\n    <li> <a href=\"view.php?aid=[field:id/]\"> <img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n      <p class=\"title\">[field:title/]</p>\r\n      <span class=\"title bg\"></span> </a> </li>\r\n   ",4598,4852);
$z[13][4]['row']="6";
$z[13][4]['titlelen']="36";
$z[13][4]['typeid']="8";
$z[14]=Array("include","",4911,4948);
$z[14][4]['filename']="foot_m.htm";

?>