<?php
$z[0]=Array("field","",40,59);
$z[0][4]['name']="title";
$z[1]=Array("global","",60,86);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",3087,3124);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("list","\r\n                <div topClassName='top1' topSwitch='on' productId='20' productName='[field:title/]' class='mProductTileForm'  id='mProductTileForm20_module303'><a href='view.php?aid=[field:id/]'>\r\n                  <div class='imgClass_160' id='imgClass20module303'><span class='imageMiddle'></span><img class='style1Img' src='[field:picname/]' width=\"100%\" height=\"100%\"/></div>\r\n                  <div class='paramCollection'>\r\n                    <p class='g_link paramName paramNowrap textAlign_left'>[field:title/]</p>\r\n                  </div>\r\n                  </a></div>\r\n                ",4308,4943);
$z[3][4]['pagesize']="4";
$z[4]=Array("pagelist","",5046,5112);
$z[4][4]['listitem']="index,end,pre,next,pageno";
$z[4][4]['listsize']="5";
$z[5]=Array("include","",5310,5349);
$z[5][4]['filename']="footer_m.htm";

?>