<?php
$z[0]=Array("field","",40,59);
$z[0][4]['name']="title";
$z[1]=Array("global","",60,86);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",3087,3124);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("list","\r\n                <div id='newsLine665' topClassName='top2' topSwitch='off' newsId='665' newsName='[field:title/] ' class='newsLine line icon-gline  wWLine  topFlagLine firstClass wholeLine' >\r\n                  <div id='lineBody665' class='lineBody lineBodyTable'>\r\n                    <div class='wholeLineTFTableCell'>\r\n                      <div class=' g_topFlag g_topFlag1' ></div>\r\n                    </div>\r\n                    <div class='linkTableCell'>\r\n                      <div class='linkTable'><a hidefocus='true' href='view.php?aid=[field:id/]' target=_self >[field:title/] </a></div>\r\n                    </div>\r\n                  </div>\r\n                </div>\r\n                <div class='g_separator separatorLine'></div>\r\n                ",4288,5085);
$z[3][4]['pagesize']="5";
$z[4]=Array("pagelist","",5187,5253);
$z[4][4]['listitem']="index,end,pre,next,pageno";
$z[4][4]['listsize']="5";
$z[5]=Array("include","",5451,5490);
$z[5][4]['filename']="footer_m.htm";

?>